services:
  db:
    image: mysql:8.0
    container_name: mysql_micheladas
    restart: always
    environment:
      - MYSQL_DATABASE=micheladas
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - miche-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: spring_micheladas
    ports:
      - "9090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_micheladas:3306/micheladas?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NOMBRE=${ADMIN_NOMBRE}
      - ADMIN_APELLIDO=${ADMIN_APELLIDO}
      - ADMIN_MOBILE=${ADMIN_MOBILE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - miche-net

networks:
  miche-net:
    driver: bridge