version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_micheladas
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME:-chelas_db}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      #- MYSQL_DATABASE=${DB_NAME}
      #- MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - miche-net
    #healthcheck:
      #test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_micheladas
    ports:
      - "9090:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL:-jdbc:mysql://db:3306/chelas_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-root}

      #- SPRING_DATASOURCE_URL=${DB_URL}
      #- SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      #- SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      - SPRING_JPA_OPEN_IN_VIEW=false

      # Datos de Admin (Falsos para despliegue)
      - APP_ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - APP_ADMIN_PASSWORD=${ADMIN_PASSWORD:-12345678}
      - APP_ADMIN_NAME=${ADMIN_NOMBRE:-Admin}
      - APP_ADMIN_SURNAME=${ADMIN_APELLIDO:-Test}
      - APP_ADMIN_MOBILE=${ADMIN_MOBILE:-1234567890}

      # Variables de entorno)
      #- APP_ADMIN_EMAIL=${ADMIN_EMAIL}
      #- APP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      #- APP_ADMIN_NAME=${ADMIN_NOMBRE}
      #- APP_ADMIN_SURNAME=${ADMIN_APELLIDO}
      #- APP_ADMIN_MOBILE=${ADMIN_MOBILE}

        # Configuración de Mail (Necesaria para que Spring no falle)
      - SPRING_MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - SPRING_MAIL_PORT=${MAIL_PORT:-587}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME:-test@example.com}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD:-pfalso}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true

      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - miche-net

networks:
  miche-net:
    driver: bridge