spring.profiles.active=local

# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ADMIN CONFIGURATION
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}
app.admin.surname=${ADMIN_SURNAME}
app.admin.mobile=${ADMIN_MOBILE}

# SESSION SECURITY
server.servlet.session.timeout=15m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.max-age=-1
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=true

# RECAPTCHA CONFIG
google.recaptcha.secret=a
google.recaptcha.site=a
google.recaptcha.url=a

# JPA/HIBERNATE
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false

# THYMELEAF
spring.thymeleaf.cache=false
