spring.messages.basename=messages,mfa
spring.profiles.active=${SPRING_PROFILE:local}

# DATABASE CONFIGURATION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ADMIN CONFIGURATION
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}
app.admin.surname=${ADMIN_SURNAME}
app.admin.mobile=${ADMIN_MOBILE}

# SESSION SECURITY
server.servlet.session.timeout=${SESSION_TIMEOUT:15m}
server.servlet.session.cookie.http-only=${COOKIE_HTTP_ONLY:true}
server.servlet.session.cookie.max-age=${COOKIE_MAX_AGE:-1}
server.servlet.session.cookie.same-site=${COOKIE_SAME_SITE:strict}
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}

# MAIL CONFIGURATION (GMAIL-MAILTRAP)
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED:true}

spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_TIMEOUT:5000}

# RECAPTCHA CONFIG
google.recaptcha.secret=${RECAPTCHA_SECRET}
google.recaptcha.site=${RECAPTCHA_SITE}
google.recaptcha.url=${RECAPTCHA_URL}

# JPA/HIBERNATE
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${JPA_DDL:update}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.mail.properties.mail.debug=${MAIL_DEBUG:true}
logging.level.org.springframework.mail=${MAIL_LOG_LEVEL:INFO}
logging.level.org.springframework.mail.javamail=${MAIL_JAVA_MAIL_LOG_LEVEL:INFO}

# THYMELEAF
spring.thymeleaf.cache=${THYMELEAF_CACHE:false}
