spring.messages.basename=mfa,messages
spring.messages.encoding=UTF-8

# Mensajes de Seguridad (Login)
login.error.locked=Tu cuenta ha sido bloqueada. Contacta al administrador.
login.error.invalid=Usuario o contrase\u00F1a incorrectos.
login.info.logout=Cerraste sesi\u00F3n correctamente.

# Mensajes de Sesi\u00F3n
auth.session.expired=Su sesi\u00F3n ha finalizado por razones de seguridad.

# Mensajes de Recuperaci\u00F3n (Password)
auth.reset.invalid=Correo y/o n\u00FAmero de tel\u00E9fono inv\u00E1lido.
auth.reset.mismatch=Las contrase\u00F1as no coinciden.
auth.reset.notfound=Usuario no encontrado.
auth.reset.success=Contrase\u00F1a cambiada correctamente.

# Mensajes de Validaci\u00F3n OTP
USER_NOT_FOUND=El usuario no se encuentra registrado en el sistema.
LOCKED=Tu cuenta ha sido bloqueada por demasiados intentos fallidos.
EXPIRED=El c\u00F3digo de seguridad ha expirado. Solicita uno nuevo.
SUCCESS=Acceso concedido correctamente.
INVALID=C\u00F3digo incorrecto. Por favor, verifica los 6 d\u00EDgitos.

mfa.instrucciones=Hemos enviado un c\u00F3digo a tu correo. Ingr\u00E9salo a continuaci\u00F3n.
mfa.error.incorrecto=C\u00F3digo incorrecto.
mfa.intentos.prefijo=Te quedan
mfa.intentos.sufijo=intentos antes de bloquear tu cuenta.


# Mensajes de Registro
registro.error.captcha=Verifica el reCAPTCHA, por favor.
registro.error.emailExiste=Este correo ya est\u00E1 registrado.
registro.exito=\u00A1Usuario registrado con \u00E9xito!
registro.captcha.hint=Completa todos los campos para habilitar la verificaci\u00F3n.
